name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Tests
        run: echo Ы!
        
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            cd emi/EMI-BOT/tg-bot
            
            export API_TOKEN="${{ secrets.API_TOKEN }}"
            # API ключ
            export NOTION_TOKEN="${{ secrets.NOTION_TOKEN }}"
            
            kill $(cat bot_pid.txt) 
            git pull
            
            nohup python3 main.py > /dev/null 2>&1 &
            echo $! > bot_pid.txt
            disown
            exit 0


